# Site settings
title: Alleyway Apps - Intuitive Software Solutions
email: hello@alleywayapps.com
url: https://www.alleywayapps.com
description: "Intuitive Software Solutions"


# Footer settings
footer: Alleyway Apps

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/AlleywayApps
  - title: github
    url: https://github.com/alleywayconsulting
  - title: instagram
    url: https://www.instagram.com/alleywayapps/
  - title: linkedin
    url: https://www.linkedin.com/company/alleyway

# Build settings
markdown: kramdown
permalink: pretty
