# Site settings
title: Alleyway Apps - Intuitive Software Solutions
email: hello@alleywayapps.com
url: https://www.alleywayapps.com
description: "Intuitive Software Solutions"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#bf8c31'

# Footer settings
footer: Alleyway Apps

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/in/mlake900
  - title: twitter
    url: https://twitter.com/AlleywayApps

# Build settings
markdown: kramdown
permalink: pretty
